### ISSUE TITLE
Documentation search field is rendered incorrectly

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/react-components#599]
**Describe the bug**
The search field in the new documentation is not rendered correctly.

**To Reproduce**
1. Go to https://sebgroup.github.io/react-components/docs/buttongroup/
2. See error

**Expected behavior**
The search icon to be aligned to the right, and the text is aligned to the left.

**Screenshots**
<img width="531" alt="Screenshot 2021-04-30 at 8 38 44 AM" src="https://user-images.githubusercontent.com/10633734/116658074-b52d6280-a98f-11eb-86fe-78ec43c947f6.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari, Chrome
 - Version 14.1, 90.0.4430.93

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.5
 - Browser Safari

**Additional context**
The fix is this:

```scss
.input-box-group-wrapper {
    flex-direction: row-reverse;

    .sidemenu-search {
        text-align: left;
    }
}
```
